# Dependencies
markdown:         redcarpet
pygments:         true
highlighter:      pygments

kramdown:
  input:        GFM

# Permalinks
permalink:        pretty

# Setup
title:            Stale Memory
description:      'Lost Writes, Stale Reads'
url:              ''
baseurl:          '/'
paginate:         5

author:
  name:           'Mehmet Dogan'
  twitter:        https://twitter.com/mmdogan
  github:         https://github.com/mdogan
