# Dependencies
#markdown:         redcarpet
markdown:         kramdown
#highlighter:      pygments
highlighter:      rouge

kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Stale Memory
description:      'Lost Writes, Stale Reads'
url:              https://blog.dogan.io
enforce_ssl:      blog.dogan.io
baseurl:          '/'
paginate:         5
analytics:        true

author:
  name:           'Mehmet Dogan'
  twitter:        https://twitter.com/mmdogan
  github:         https://github.com/mdogan

plugins:
  - jekyll-feed
  - jekyll-paginate

feed:
  path: atom.xml
